# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-19 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.SmallIntegerField(choices=[(1, 'Мужчина'), (2, 'Женщина')], default=1),
        ),
    ]
