# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-04 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='rating',
            field=models.SmallIntegerField(default=0),
        ),
    ]
