# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-09 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20160804_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('м', 'Мужчина'), ('ж', 'Женщина')], default='м', max_length=2),
        ),
    ]
