# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-03 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_registration', '0002_auto_20160803_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(null=True, upload_to='avatars/'),
        ),
    ]
