# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-10 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_registration', '0009_auto_20160809_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(error_messages={'blank': 'invalid', 'duplicate_username': 'HELLO', 'required': 'pls write'}, max_length=255, unique=True, verbose_name='email address'),
        ),
    ]
