# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-10 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_registration', '0011_auto_20160810_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='MyUsername',
            field=models.CharField(error_messages={'unique': 'Профиль с таким именем пользователя уже существует!'}, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(error_messages={'unique': 'Профиль с таким email уже существует!'}, max_length=255, unique=True, verbose_name='email address'),
        ),
    ]
